version: "3.2"
services:

  api:
    depends_on:
      - store
    build: ./images/api
    container_name: api
    ports:
      - 80:3000
    volumes:
      - ./images/api/src:/usr/app/src
    environment: 
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store:5432/${POSTGRES_DB}"

  store:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      POSTGRES_HOSTY_AUTH_METHOD: "trust"
    volumes:
      - ./_backup:/var/lib/postgresql/data
      

  frontend:
    depends_on:
      - api
    build:
      context: ./images/frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./images/frontend/src:/usr/src/app/src
